version: '3.8'

services:
  core-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core-api
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/global-bundle.pem:/app/certs/global-bundle.pem
    restart: unless-stopped